POST https://slack.com/api/chat.postMessage
Content-Type: application/json
Authorization: Bearer xoxb-1175038918580-1169073439443-DrN6RDMhJek65KgRNPwXYq48

{
  "channel": "C014YR97WV8",
  "attachments": [
    {
      "pretext": "<@dongmyeong.lee22>"
    }
  ]
}

###
